# Generated by Django 3.1.5 on 2021-01-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210106_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipariş',
            name='teslim_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
