# Generated by Django 3.1.5 on 2021-01-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bakım_bayi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakım',
            name='bayi',
        ),
        migrations.RemoveField(
            model_name='bakım',
            name='müşteri',
        ),
        migrations.RemoveField(
            model_name='bakım',
            name='ürün',
        ),
        migrations.AddField(
            model_name='bakım',
            name='açıklama',
            field=models.TextField(default='genel bakım'),
        ),
        migrations.AddField(
            model_name='bakım',
            name='gelecek_bakım_tarihi',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='bakım',
            name='satış',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.satış'),
        ),
    ]
