# Generated by Django 3.1.5 on 2021-01-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210106_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipariş',
            name='onaylandı',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sipariş',
            name='tutar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
