# Generated by Django 3.1.5 on 2021-01-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210115_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipariş',
            name='onaylandı',
        ),
        migrations.AddField(
            model_name='sipariş',
            name='durum',
            field=models.CharField(choices=[('o', 'onaylandı'), ('b', 'beklemede'), ('r', 'reddedildi')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='sipariş',
            name='sipariş_takibi',
            field=models.CharField(choices=[('h', 'hazırlanıyor'), ('y', 'yola çıktı'), ('t', 'teslim edildi')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='bakım',
            name='gelecek_bakım_tarihi',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
