# Generated by Django 3.1.5 on 2021-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210106_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipariş',
            name='onaylandı',
            field=models.BooleanField(choices=[('Onaylandı', True), ('Onay Aşamasında', False)], null=True),
        ),
    ]
