# Generated by Django 3.1.5 on 2021-01-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210108_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipariş',
            name='onaylandı',
            field=models.BooleanField(choices=[(True, 'Onaylandı'), (False, 'Onay Aşamasında')], null=True),
        ),
    ]
