# Generated by Django 3.1.5 on 2021-01-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210108_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bayi',
            name='aktif',
            field=models.BooleanField(default=False),
        ),
    ]
