# Generated by Django 3.1.5 on 2021-01-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210108_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ürün',
            name='depodaki_miktar',
        ),
    ]
