# Generated by Django 3.1.5 on 2021-01-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210113_0059'),
        ('core', '0008_remove_ürün_depodaki_miktar'),
    ]

    operations = [
    ]
