# Generated by Django 3.2.8 on 2021-10-31 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=150)),
                ('factory_address', models.CharField(max_length=150)),
                ('factory_city', models.CharField(max_length=30)),
                ('factory_country', models.CharField(max_length=30)),
                ('factory_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factory',
                'verbose_name_plural': 'Factorys',
            },
        ),
    ]
